/* tslint:disable */
/* eslint-disable */
/**
 * newgor-wishlist
 * Программный интерфейс сервиса \"Вишлист\"
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CommonFault,
  CreateItem200Response,
  GetItems200Response,
  Item,
  ItemUpdate,
  SortField,
} from '../models/index';
import {
    CommonFaultFromJSON,
    CommonFaultToJSON,
    CreateItem200ResponseFromJSON,
    CreateItem200ResponseToJSON,
    GetItems200ResponseFromJSON,
    GetItems200ResponseToJSON,
    ItemFromJSON,
    ItemToJSON,
    ItemUpdateFromJSON,
    ItemUpdateToJSON,
    SortFieldFromJSON,
    SortFieldToJSON,
} from '../models/index';

export interface CreateItemRequest {
    item?: Item;
}

export interface GetItemByIdRequest {
    id: string;
}

export interface GetItemImageRequest {
    id: string;
}

export interface GetItemsRequest {
    userLogin: string;
    statusCode?: string;
    createDateFrom?: Date;
    createDateTo?: Date;
    limit?: number;
    offset?: number;
    showReservedStatus?: boolean;
    sortField?: SortField;
}

export interface PatchItemRequest {
    id: string;
    itemUpdate: ItemUpdate;
}

export interface ReserveItemRequest {
    id: string;
    reserved: boolean;
}

export interface SetItemStatusRequest {
    id: string;
    statusCode?: string;
}

export interface UploadItemImageRequest {
    id: string;
    file: Blob;
    metadata: string;
}

/**
 * 
 */
export class ItemsApi extends runtime.BaseAPI {

    /**
     * Создать новый предмет
     */
    async createItemRaw(requestParameters: CreateItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateItem200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Authorization", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/wishlist/item`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ItemToJSON(requestParameters['item']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateItem200ResponseFromJSON(jsonValue));
    }

    /**
     * Создать новый предмет
     */
    async createItem(requestParameters: CreateItemRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateItem200Response> {
        const response = await this.createItemRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Получение подробной информации о предмете по указанному идентификатору.
     * Получить предмет вишлиста по id
     */
    async getItemByIdRaw(requestParameters: GetItemByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Item>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getItemById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Authorization", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/wishlist/item/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ItemFromJSON(jsonValue));
    }

    /**
     * Получение подробной информации о предмете по указанному идентификатору.
     * Получить предмет вишлиста по id
     */
    async getItemById(requestParameters: GetItemByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Item> {
        const response = await this.getItemByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Получить изображение предмета
     */
    async getItemImageRaw(requestParameters: GetItemImageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getItemImage().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/wishlist/item/{id}/image`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Получить изображение предмета
     */
    async getItemImage(requestParameters: GetItemImageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.getItemImageRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Метод позволяет получить список предметов вишлиста по заданным параметрам запроса. Если по заданным параметрам предметы не найдены, то возвращается пустой массив.
     * Получить список предметов
     */
    async getItemsRaw(requestParameters: GetItemsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetItems200Response>> {
        if (requestParameters['userLogin'] == null) {
            throw new runtime.RequiredError(
                'userLogin',
                'Required parameter "userLogin" was null or undefined when calling getItems().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['userLogin'] != null) {
            queryParameters['userLogin'] = requestParameters['userLogin'];
        }

        if (requestParameters['statusCode'] != null) {
            queryParameters['statusCode'] = requestParameters['statusCode'];
        }

        if (requestParameters['createDateFrom'] != null) {
            queryParameters['createDateFrom'] = requestParameters['createDateFrom'];
        }

        if (requestParameters['createDateTo'] != null) {
            queryParameters['createDateTo'] = requestParameters['createDateTo'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['showReservedStatus'] != null) {
            queryParameters['showReservedStatus'] = requestParameters['showReservedStatus'];
        }

        if (requestParameters['sortField'] != null) {
            queryParameters['sortField'] = requestParameters['sortField'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Authorization", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/wishlist/item`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetItems200ResponseFromJSON(jsonValue));
    }

    /**
     * Метод позволяет получить список предметов вишлиста по заданным параметрам запроса. Если по заданным параметрам предметы не найдены, то возвращается пустой массив.
     * Получить список предметов
     */
    async getItems(requestParameters: GetItemsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetItems200Response> {
        const response = await this.getItemsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Метод для изменения предмета
     * Обновить предмет
     */
    async patchItemRaw(requestParameters: PatchItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling patchItem().'
            );
        }

        if (requestParameters['itemUpdate'] == null) {
            throw new runtime.RequiredError(
                'itemUpdate',
                'Required parameter "itemUpdate" was null or undefined when calling patchItem().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Authorization", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/wishlist/item/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: ItemUpdateToJSON(requestParameters['itemUpdate']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Метод для изменения предмета
     * Обновить предмет
     */
    async patchItem(requestParameters: PatchItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.patchItemRaw(requestParameters, initOverrides);
    }

    /**
     * Изменить статус резерва
     */
    async reserveItemRaw(requestParameters: ReserveItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling reserveItem().'
            );
        }

        if (requestParameters['reserved'] == null) {
            throw new runtime.RequiredError(
                'reserved',
                'Required parameter "reserved" was null or undefined when calling reserveItem().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['reserved'] != null) {
            queryParameters['reserved'] = requestParameters['reserved'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Authorization", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/wishlist/item/{id}/reserve`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Изменить статус резерва
     */
    async reserveItem(requestParameters: ReserveItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.reserveItemRaw(requestParameters, initOverrides);
    }

    /**
     * Обновить статус предмета
     */
    async setItemStatusRaw(requestParameters: SetItemStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling setItemStatus().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['statusCode'] != null) {
            queryParameters['statusCode'] = requestParameters['statusCode'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Authorization", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/wishlist/item/{id}/status`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Обновить статус предмета
     */
    async setItemStatus(requestParameters: SetItemStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.setItemStatusRaw(requestParameters, initOverrides);
    }

    /**
     * Загрузить/обновить изображение предмета
     */
    async uploadItemImageRaw(requestParameters: UploadItemImageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateItem200Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling uploadItemImage().'
            );
        }

        if (requestParameters['file'] == null) {
            throw new runtime.RequiredError(
                'file',
                'Required parameter "file" was null or undefined when calling uploadItemImage().'
            );
        }

        if (requestParameters['metadata'] == null) {
            throw new runtime.RequiredError(
                'metadata',
                'Required parameter "metadata" was null or undefined when calling uploadItemImage().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'multipart/form-data' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['file'] != null) {
            formParams.append('file', requestParameters['file'] as any);
        }

        if (requestParameters['metadata'] != null) {
            formParams.append('metadata', requestParameters['metadata'] as any);
        }


        let urlPath = `/wishlist/item/{id}/image`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateItem200ResponseFromJSON(jsonValue));
    }

    /**
     * Загрузить/обновить изображение предмета
     */
    async uploadItemImage(requestParameters: UploadItemImageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateItem200Response> {
        const response = await this.uploadItemImageRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
