/* tslint:disable */
/* eslint-disable */
/**
 * newgor-wishlist
 * Программный интерфейс сервиса \"Вишлист\"
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Тело для общего описания ошибок
 * @export
 * @interface CommonFault
 */
export interface CommonFault {
    /**
     * Дата и время ошибки (UTC+0)
     * @type {Date}
     * @memberof CommonFault
     */
    timestamp?: Date;
    /**
     * Уникальный идентификатор ошибки
     * @type {string}
     * @memberof CommonFault
     */
    id?: string;
    /**
     * Путь
     * @type {string}
     * @memberof CommonFault
     */
    path?: string;
    /**
     * HTTP Status Code
     * @type {number}
     * @memberof CommonFault
     */
    statusCode?: number;
    /**
     * Описание ошибки
     * @type {string}
     * @memberof CommonFault
     */
    detail?: string;
    /**
     * Бизнеc-код ошибки
     * @type {string}
     * @memberof CommonFault
     */
    code?: string;
    /**
     * Бизнес-описание ошибки
     * @type {string}
     * @memberof CommonFault
     */
    message?: string;
}

/**
 * Check if a given object implements the CommonFault interface.
 */
export function instanceOfCommonFault(value: object): value is CommonFault {
    return true;
}

export function CommonFaultFromJSON(json: any): CommonFault {
    return CommonFaultFromJSONTyped(json, false);
}

export function CommonFaultFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonFault {
    if (json == null) {
        return json;
    }
    return {
        
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'id': json['id'] == null ? undefined : json['id'],
        'path': json['path'] == null ? undefined : json['path'],
        'statusCode': json['statusCode'] == null ? undefined : json['statusCode'],
        'detail': json['detail'] == null ? undefined : json['detail'],
        'code': json['code'] == null ? undefined : json['code'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function CommonFaultToJSON(json: any): CommonFault {
    return CommonFaultToJSONTyped(json, false);
}

export function CommonFaultToJSONTyped(value?: CommonFault | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timestamp': value['timestamp'] == null ? value['timestamp'] : value['timestamp'].toISOString(),
        'id': value['id'],
        'path': value['path'],
        'statusCode': value['statusCode'],
        'detail': value['detail'],
        'code': value['code'],
        'message': value['message'],
    };
}

