/* tslint:disable */
/* eslint-disable */
/**
 * newgor-wishlist
 * Программный интерфейс сервиса \"Вишлист\"
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateItem200Response
 */
export interface CreateItem200Response {
    /**
     * 
     * @type {string}
     * @memberof CreateItem200Response
     */
    id?: string;
}

/**
 * Check if a given object implements the CreateItem200Response interface.
 */
export function instanceOfCreateItem200Response(value: object): value is CreateItem200Response {
    return true;
}

export function CreateItem200ResponseFromJSON(json: any): CreateItem200Response {
    return CreateItem200ResponseFromJSONTyped(json, false);
}

export function CreateItem200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateItem200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function CreateItem200ResponseToJSON(json: any): CreateItem200Response {
    return CreateItem200ResponseToJSONTyped(json, false);
}

export function CreateItem200ResponseToJSONTyped(value?: CreateItem200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

