/* tslint:disable */
/* eslint-disable */
/**
 * newgor-wishlist
 * Программный интерфейс сервиса \"Вишлист\"
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ItemBaseInfo } from './ItemBaseInfo';
import {
    ItemBaseInfoFromJSON,
    ItemBaseInfoFromJSONTyped,
    ItemBaseInfoToJSON,
    ItemBaseInfoToJSONTyped,
} from './ItemBaseInfo';

/**
 * 
 * @export
 * @interface GetItems200Response
 */
export interface GetItems200Response {
    /**
     * Общее количество записей
     * @type {number}
     * @memberof GetItems200Response
     */
    totalCount?: number;
    /**
     * 
     * @type {Array<ItemBaseInfo>}
     * @memberof GetItems200Response
     */
    list?: Array<ItemBaseInfo>;
}

/**
 * Check if a given object implements the GetItems200Response interface.
 */
export function instanceOfGetItems200Response(value: object): value is GetItems200Response {
    return true;
}

export function GetItems200ResponseFromJSON(json: any): GetItems200Response {
    return GetItems200ResponseFromJSONTyped(json, false);
}

export function GetItems200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetItems200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
        'list': json['list'] == null ? undefined : ((json['list'] as Array<any>).map(ItemBaseInfoFromJSON)),
    };
}

export function GetItems200ResponseToJSON(json: any): GetItems200Response {
    return GetItems200ResponseToJSONTyped(json, false);
}

export function GetItems200ResponseToJSONTyped(value?: GetItems200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalCount': value['totalCount'],
        'list': value['list'] == null ? undefined : ((value['list'] as Array<any>).map(ItemBaseInfoToJSON)),
    };
}

