/* tslint:disable */
/* eslint-disable */
/**
 * newgor-wishlist
 * Программный интерфейс сервиса \"Вишлист\"
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface ItemUpdate
 */
export interface ItemUpdate {
    /**
     * Идентификатор в БД сервиса
     * @type {string}
     * @memberof ItemUpdate
     */
    id?: string;
    /**
     * Дата и время создания в БД сервиса
     * @type {Date}
     * @memberof ItemUpdate
     */
    createDate?: Date;
    /**
     * Дата последнего обновления в БД сервиса
     * @type {Date}
     * @memberof ItemUpdate
     */
    lastUpdateDate?: Date;
    /**
     * наименование
     * @type {string}
     * @memberof ItemUpdate
     */
    name?: string;
    /**
     * сумма
     * @type {string}
     * @memberof ItemUpdate
     */
    amount?: string;
    /**
     * зарезервирован ли товар
     * @type {boolean}
     * @memberof ItemUpdate
     */
    reserved?: boolean;
    /**
     * приоритет
     * @type {string}
     * @memberof ItemUpdate
     */
    priority?: string;
    /**
     * наименование приоритета
     * @type {string}
     * @memberof ItemUpdate
     */
    priorityName?: string;
    /**
     * валюта
     * @type {string}
     * @memberof ItemUpdate
     */
    currency?: string;
    /**
     * описание
     * @type {string}
     * @memberof ItemUpdate
     */
    description?: string;
    /**
     * ссылка на сайт
     * @type {string}
     * @memberof ItemUpdate
     */
    linkToSite?: string;
    /**
     * изображение предмета
     * @type {string}
     * @memberof ItemUpdate
     */
    image?: string;
}

/**
 * Check if a given object implements the ItemUpdate interface.
 */// @ts-ignore
export function instanceOfItemUpdate(value: object): value is ItemUpdate {
    return true;
}

export function ItemUpdateFromJSON(json: any): ItemUpdate {
    return ItemUpdateFromJSONTyped(json, false);
}
// @ts-ignore
export function ItemUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'createDate': json['createDate'] == null ? undefined : (new Date(json['createDate'])),
        'lastUpdateDate': json['lastUpdateDate'] == null ? undefined : (new Date(json['lastUpdateDate'])),
        'name': json['name'] == null ? undefined : json['name'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'reserved': json['reserved'] == null ? undefined : json['reserved'],
        'priority': json['priority'] == null ? undefined : json['priority'],
        'priorityName': json['priorityName'] == null ? undefined : json['priorityName'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'description': json['description'] == null ? undefined : json['description'],
        'linkToSite': json['linkToSite'] == null ? undefined : json['linkToSite'],
        'image': json['image'] == null ? undefined : json['image'],
    };
}

export function ItemUpdateToJSON(json: any): ItemUpdate {
    return ItemUpdateToJSONTyped(json, false);
}
// @ts-ignore
export function ItemUpdateToJSONTyped(value?: ItemUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'createDate': value['createDate'] == null ? value['createDate'] : value['createDate'].toISOString(),
        'lastUpdateDate': value['lastUpdateDate'] == null ? value['lastUpdateDate'] : value['lastUpdateDate'].toISOString(),
        'name': value['name'],
        'amount': value['amount'],
        'reserved': value['reserved'],
        'priority': value['priority'],
        'priorityName': value['priorityName'],
        'currency': value['currency'],
        'description': value['description'],
        'linkToSite': value['linkToSite'],
        'image': value['image'],
    };
}

