/* tslint:disable */
/* eslint-disable */
/**
 * newgor-wishlist
 * Программный интерфейс сервиса \"Вишлист\"
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Базовая информация о предмете
 * @export
 * @interface ItemBaseInfo
 */
export interface ItemBaseInfo {
    /**
     * Идентификатор в БД сервиса
     * @type {string}
     * @memberof ItemBaseInfo
     */
    id?: string;
    /**
     * Дата и время создания в БД сервиса
     * @type {Date}
     * @memberof ItemBaseInfo
     */
    createDate?: Date;
    /**
     * Дата последнего обновления в БД сервиса
     * @type {Date}
     * @memberof ItemBaseInfo
     */
    lastUpdateDate?: Date;
    /**
     * наименование
     * @type {string}
     * @memberof ItemBaseInfo
     */
    name?: string;
    /**
     * сумма
     * @type {string}
     * @memberof ItemBaseInfo
     */
    amount?: string;
    /**
     * зарезервирован ли товар
     * @type {boolean}
     * @memberof ItemBaseInfo
     */
    reserved?: boolean;
}

/**
 * Check if a given object implements the ItemBaseInfo interface.
 */
export function instanceOfItemBaseInfo(value: object): value is ItemBaseInfo {
    return true;
}

export function ItemBaseInfoFromJSON(json: any): ItemBaseInfo {
    return ItemBaseInfoFromJSONTyped(json, false);
}

export function ItemBaseInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemBaseInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'createDate': json['createDate'] == null ? undefined : (new Date(json['createDate'])),
        'lastUpdateDate': json['lastUpdateDate'] == null ? undefined : (new Date(json['lastUpdateDate'])),
        'name': json['name'] == null ? undefined : json['name'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'reserved': json['reserved'] == null ? undefined : json['reserved'],
    };
}

export function ItemBaseInfoToJSON(json: any): ItemBaseInfo {
    return ItemBaseInfoToJSONTyped(json, false);
}

export function ItemBaseInfoToJSONTyped(value?: ItemBaseInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'createDate': value['createDate'] == null ? value['createDate'] : value['createDate'].toISOString(),
        'lastUpdateDate': value['lastUpdateDate'] == null ? value['lastUpdateDate'] : value['lastUpdateDate'].toISOString(),
        'name': value['name'],
        'amount': value['amount'],
        'reserved': value['reserved'],
    };
}

