/* tslint:disable */
/* eslint-disable */
/**
 * newgor-wishlist
 * Программный интерфейс сервиса \"Вишлист\"
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Статус предмета в вишлисте
 * @export
 */
export const ItemStatus = {
    Draft: 'DRAFT',
    Open: 'OPEN',
    Completed: 'COMPLETED',
    Canceled: 'CANCELED'
} as const;
export type ItemStatus = typeof ItemStatus[keyof typeof ItemStatus];


export function instanceOfItemStatus(value: any): boolean {
    for (const key in ItemStatus) {
        if (Object.prototype.hasOwnProperty.call(ItemStatus, key)) {
            if (ItemStatus[key as keyof typeof ItemStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ItemStatusFromJSON(json: any): ItemStatus {
    return ItemStatusFromJSONTyped(json, false);
}
// @ts-ignore
export function ItemStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemStatus {
    return json as ItemStatus;
}

export function ItemStatusToJSON(value?: ItemStatus | null): any {
    return value as any;
}
// @ts-ignore
export function ItemStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): ItemStatus {
    return value as ItemStatus;
}

