/* tslint:disable */
/* eslint-disable */
/**
 * newgor-wishlist
 * Программный интерфейс сервиса \"Вишлист\"
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ItemStatus } from './ItemStatus';
import {
    ItemStatusFromJSON,
    ItemStatusFromJSONTyped,
    ItemStatusToJSON,
    ItemStatusToJSONTyped,
} from './ItemStatus';

/**
 * 
 * @export
 * @interface Item
 */
export interface Item {
    /**
     * Идентификатор в БД сервиса
     * @type {string}
     * @memberof Item
     */
    id?: string;
    /**
     * Дата и время создания в БД сервиса
     * @type {Date}
     * @memberof Item
     */
    createDate?: Date;
    /**
     * Дата последнего обновления в БД сервиса
     * @type {Date}
     * @memberof Item
     */
    lastUpdateDate?: Date;
    /**
     * наименование
     * @type {string}
     * @memberof Item
     */
    name: string;
    /**
     * сумма
     * @type {number}
     * @memberof Item
     */
    amount: number;
    /**
     * валюта
     * @type {string}
     * @memberof Item
     */
    currency: string;
    /**
     * зарезервирован ли товар
     * @type {boolean}
     * @memberof Item
     */
    reserved?: boolean;
    /**
     * код приоритета 1-10
     * @type {number}
     * @memberof Item
     */
    priority: number;
    /**
     * наименование приоритета
     * @type {string}
     * @memberof Item
     */
    priorityName?: string;
    /**
     * описание
     * @type {string}
     * @memberof Item
     */
    description?: string;
    /**
     * ссылка на сайт
     * @type {string}
     * @memberof Item
     */
    linkToSite?: string;
    /**
     * изображение предмета
     * @type {string}
     * @memberof Item
     */
    image?: string;
    /**
     * 
     * @type {ItemStatus}
     * @memberof Item
     */
    statusCode?: ItemStatus;
    /**
     * наименование статуса
     * @type {string}
     * @memberof Item
     */
    statusName?: string;
    /**
     * логин пользователя
     * @type {string}
     * @memberof Item
     */
    userLogin?: string;
}



/**
 * Check if a given object implements the Item interface.
 */
export function instanceOfItem(value: object): value is Item {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if (!('priority' in value) || value['priority'] === undefined) return false;
    return true;
}

export function ItemFromJSON(json: any): Item {
    return ItemFromJSONTyped(json, false);
}

export function ItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): Item {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'createDate': json['createDate'] == null ? undefined : (new Date(json['createDate'])),
        'lastUpdateDate': json['lastUpdateDate'] == null ? undefined : (new Date(json['lastUpdateDate'])),
        'name': json['name'],
        'amount': json['amount'],
        'currency': json['currency'],
        'reserved': json['reserved'] == null ? undefined : json['reserved'],
        'priority': json['priority'],
        'priorityName': json['priorityName'] == null ? undefined : json['priorityName'],
        'description': json['description'] == null ? undefined : json['description'],
        'linkToSite': json['linkToSite'] == null ? undefined : json['linkToSite'],
        'image': json['image'] == null ? undefined : json['image'],
        'statusCode': json['statusCode'] == null ? undefined : ItemStatusFromJSON(json['statusCode']),
        'statusName': json['statusName'] == null ? undefined : json['statusName'],
        'userLogin': json['userLogin'] == null ? undefined : json['userLogin'],
    };
}

export function ItemToJSON(json: any): Item {
    return ItemToJSONTyped(json, false);
}

export function ItemToJSONTyped(value?: Item | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'createDate': value['createDate'] == null ? value['createDate'] : value['createDate'].toISOString(),
        'lastUpdateDate': value['lastUpdateDate'] == null ? value['lastUpdateDate'] : value['lastUpdateDate'].toISOString(),
        'name': value['name'],
        'amount': value['amount'],
        'currency': value['currency'],
        'reserved': value['reserved'],
        'priority': value['priority'],
        'priorityName': value['priorityName'],
        'description': value['description'],
        'linkToSite': value['linkToSite'],
        'image': value['image'],
        'statusCode': ItemStatusToJSON(value['statusCode']),
        'statusName': value['statusName'],
        'userLogin': value['userLogin'],
    };
}

