/* tslint:disable */
/* eslint-disable */
/**
 * newgor-wishlist
 * Программный интерфейс сервиса \"Вишлист\"
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Статус предмета в вишлисте
 * @export
 */
export const SortField = {
    CreateDate: 'CREATE_DATE',
    Priority: 'PRIORITY'
} as const;
export type SortField = typeof SortField[keyof typeof SortField];


export function instanceOfSortField(value: any): boolean {
    for (const key in SortField) {
        if (Object.prototype.hasOwnProperty.call(SortField, key)) {
            if (SortField[key as keyof typeof SortField] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SortFieldFromJSON(json: any): SortField {
    return SortFieldFromJSONTyped(json, false);
}
// @ts-ignore
export function SortFieldFromJSONTyped(json: any, ignoreDiscriminator: boolean): SortField {
    return json as SortField;
}

export function SortFieldToJSON(value?: SortField | null): any {
    return value as any;
}
// @ts-ignore
export function SortFieldToJSONTyped(value: any, ignoreDiscriminator: boolean): SortField {
    return value as SortField;
}

